version: '3.8'

services:
  db_mongo:
    image: mongo:latest
    container_name: mongo-db_container
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db_mongo
    restart: always
  
  db_sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql-db_container
    ports:
      - 1433:1433
    volumes:
      - sql_db:/data/db_sql
    environment:
      SA_PASSWORD: "123qweasd"
      ACCEPT_EULA: "Y"
    restart: always

  backend:
    image: yakovfullstack/asp-server
    container_name: server_container
    ports:
      - 49155:443
      - 49156:80
    depends_on:
      - db_mongo
      - db_sql
    restart: always

  client:
    image: yakovfullstack/angular-client
    container_name: client_container
    ports:
      - 4200:80
    depends_on:
      - backend

volumes:
  mongo_db : {}
  sql_db : {}